### ISSUE TITLE
manual.py not working any more

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1129]
hello. the manual.py used to work. but for the past few days i keep getting this error

Traceback (most recent call last):
  File "./manual.py", line 14, in <module>
    from tvdb_mp4 import Tvdb_mp4
  File "/opt/scripts/sickbeard_mp4_automator/tvdb_mp4.py", line 12, in <module>
    from mutagen.mp4 import MP4, MP4Cover
ImportError: No module named mutagen.mp4

**Comment by Smalfinn** [comment]
Hi,

Setup has changed, you need the mutagen package for manual.py to be able to tag MP4 files
[https://github.com/mdhiggins/sickbeard_mp4_automator#prerequisite-pip-package-installation-instructions](https://github.com/mdhiggins/sickbeard_mp4_automator#prerequisite-pip-package-installation-instructions)

`pip install mutagen`

**Comment by pazport** [comment]
i did has you mate. but now i keep getting this error. i have also made sure, i have installed all the pip commands on your site.

 Traceback (most recent call last):
  File "./manual.py", line 394, in <module>
    main()
  File "./manual.py", line 360, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "./manual.py", line 255, in walkDir
    tagdata = getinfo(filepath, silent, tvdbid=tvdbid)
  File "./manual.py", line 91, in getinfo
    tagdata = guessInfo(fileName, tvdbid)
  File "./manual.py", line 129, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: 'module' object has no attribute 'guessit'

**Comment by mdhiggins** [comment]
`pip install guessit`

**Comment by pazport** [comment]
that is already installed mate. i upgraded today lol

**Comment by mdhiggins** [comment]
What version do you have installed?

**Comment by mdhiggins** [comment]
Should be 3.1.0

**Comment by pazport** [comment]
Requirement already satisfied: guessit in /usr/local/lib/python3.6/dist-packages (3.1.0)
Requirement already satisfied: rebulk==2.* in /usr/local/lib/python3.6/dist-packages (from guessit) (2.0.0)
Requirement already satisfied: babelfish in /usr/local/lib/python3.6/dist-packages (from guessit) (0.5.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from guessit) (2.8.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from guessit) (1.14.0)

**Comment by mdhiggins** [comment]
Try running this test script
```
import guessit
import sys

print(sys.executable)
print(guessit.__version__)
g = guessit.guessit("Star.Trek.Picard.S01E04.iNTERNAL.1080p.WEB.H264-GHOSTS.mkv")
print(g['title'])

```

**Comment by mdhiggins** [comment]
I also pushed an update to manual.py that includes some debugging output of the version of guessit its importing and the python path, if you could update and run that as well and post the output from that script and the one I just posted above I can try and sort out what's going on

I'm wondering if your guessit install is corrupt or there's another python environment with an older version that's getting called

**Comment by pazport** [comment]
sorry i don't know how to run scripts lol. am still learning on linux. 

and ye sure mate. i will update them now and test

**Comment by mdhiggins** [comment]
Just copy that into a text file and name it something .py (guessit-test.py) and then run it

**Comment by pazport** [comment]
i updated the files mate. but still the same. in ssh Traceback (most recent call last):
  File "./manual.py", line 395, in <module>
    main()
  File "./manual.py", line 361, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "./manual.py", line 255, in walkDir
    tagdata = getinfo(filepath, silent, tvdbid=tvdbid)
  File "./manual.py", line 91, in getinfo
    tagdata = guessInfo(fileName, tvdbid)
  File "./manual.py", line 129, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: 'module' object has no attribute 'guessit'

but in index.log file all i see if this 

2020-02-14 14:51:25 - MANUAL - INFO - /usr/bin/python2.7
2020-02-14 15:04:45 - MANUAL - INFO - Manual processor started.
2020-02-14 15:04:45 - MANUAL - INFO - /usr/bin/python

**Comment by pazport** [comment]
and i just ran that script mate. this is the error i got

/usr/bin/python
1.0.3
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    g = guessit.guessit("Star.Trek.Picard.S01E04.iNTERNAL.1080p.WEB.H264-GHOSTS.mkv")
AttributeError: 'module' object has no attribute 'guessit'

**Comment by mdhiggins** [comment]
Perfect
You must have 2 instances of python installed
See that 1.0.3 there? That's the guessit version its importing (not 3.1.0)
Whatever pip you're running is applying its changes to a different python environment

**Comment by mdhiggins** [comment]
Both of those scripts are being called by /usr/bin/python if that's any help to you
You can to type `which pip` in linux to see where that's being called from

**Comment by pazport** [comment]
ye i just noticed then. and when i set the script to #!/usr/bin/env python3.6 it came out with

/usr/bin/python3.6
3.1.0
Star Trek Picard
so looks like they need point to python3

**Comment by pazport** [comment]
and when i did ``which pip`` i got ``/usr/local/bin/pip``

**Comment by mdhiggins** [comment]
Alright so that should work now if you point it to the right python environment
I would use python3 anyway, its better

I run all this stuff inside a virtual environment anyway. Rather than modifying each files' Shebang I would just call it with the python path specified when launching. Changing the default python instance at the operating system level can cause issues. You could also consider adding /usr/local/bin to your PATH so that becomes the default

**Comment by pazport** [comment]
right al make changes to them now. and point them to python3.6 and test

**Comment by mdhiggins** [comment]
Biggest reason not to modify the shebang is that any updates to the script will overwrite those and you'll have to do it every time

**Comment by pazport** [comment]
ah right. nw mate. glad i could help out lol.

**Comment by mdhiggins** [comment]
Yeah this happens all the time, most people don't realize they have multiple python installations and end up installing things on the wrong one and thinking its a problem with the script. Gonna close this for now looks like its sorted
