### ISSUE TITLE
postRadarr.py not running. Radarr constantly parsing movie

### ISSUE THREAD

**Issue by Captain-Wiggles** [mdhiggins/sickbeard_mp4_automator#1143]
Couldn't find this upon multiple searches and I'm only a beginner with coding so I apologize if this is a simple oversight. I followed the ReadME file for radarr and utorrent but can't seem to get the postRadarr to work.

On completed conversion, uTorrent seems to be processing correctly and passing it to radarr. Radarr responds with it adding it to the queue. The queue then seems to get stuck looping without running the postRadarr for sorting.

mp4_automator log file:

2020-02-22 13:47:06 - uTorrentPostProcess - INFO - uTorrent post processing started.
2020-02-22 13:47:06 - uTorrentPostProcess - INFO - Performing conversion
2020-02-22 13:47:08 - uTorrentPostProcess - INFO - Processing file C:\Users\CaptainWiggles\Videos\Completed\Piper.2016.1080p.BluRay.H264.AAC-RARBG\Piper.2016.1080p.BluRay.H264.AAC-RARBG.mp4.
2020-02-22 13:47:35 - uTorrentPostProcess - INFO - Passing C:\Users\CaptainWiggles\Videos\Torrent_Converted directory to Radarr.
2020-02-22 13:47:35 - autoprocess.radarr - INFO - Radarr notifier started.
2020-02-22 13:47:35 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'C:\Users\CaptainWiggles\Videos\Torrent_Converted'.
2020-02-22 13:47:35 - autoprocess.radarr - INFO - Radarr response: queued.

Radarr log file:

2020-2-22 13:32:36.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (41 ms)
2020-2-22 13:32:36.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (10 ms)
2020-2-22 13:32:36.9|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (11 ms)
2020-2-22 13:32:36.9|Debug|Api|[GET] /api/system/task?sort_by=interval&order=asc: 200.OK (9 ms)
2020-2-22 13:32:36.9|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (6 ms)
2020-2-22 13:32:36.9|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (5 ms)
2020-2-22 13:33:06.7|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (21 ms)
2020-2-22 13:33:06.7|Debug|Api|[GET] /api/system/task?sort_by=interval&order=asc: 200.OK (19 ms)
2020-2-22 13:33:06.7|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (5 ms)
2020-2-22 13:33:06.7|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (7 ms)
2020-2-22 13:33:59.7|Debug|Api|[POST] /api/command: 201.Created (152 ms)
2020-2-22 13:33:59.8|Debug|Parser|Parsing string 'Torrent_Converted'
2020-2-22 13:33:59.8|Debug|Parser|Unable to parse Torrent_Converted
2020-2-22 13:33:59.8|Debug|DownloadedMovieImportService|Unknown Movie Torrent_Converted
2020-2-22 13:34:00.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (8 ms)
2020-2-22 13:34:00.1|Debug|Api|[GET] /api/system/task?sort_by=interval&order=asc: 200.OK (11 ms)
2020-2-22 13:34:00.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (8 ms)
2020-2-22 13:34:00.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (6 ms)
2020-2-22 13:34:06.8|Debug|Parser|Parsing string 'Piper.2016.1080p.BluRay.H264.AAC-RARBG'
2020-2-22 13:34:06.8|Debug|Parser|Movie Parsed. Piper - 2016 
2020-2-22 13:34:06.8|Debug|ParsingService|Language(s) parsed: 
2020-2-22 13:34:06.8|Debug|QualityParser|Trying to parse quality for A Movie.2016.1080p.BluRay.H264.AAC-RARBG
2020-2-22 13:34:06.8|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)

The last few lines will then just loop constantly.

**Comment by Captain-Wiggles** [comment]
So after a bit more troubleshooting, I think the issue I had was with my utorrent settings. I previously had webui set to false which I now understand as uTorrent not updating the radarr's torrent activity hence the constant parsing.
I set webui to true as below but the uTorrent postprocess would crash immediately. I was able to screen grab the moment of the crash and saw the error was with the authtoken (line 102, 23, 546, 533, 646, 516)

I'm not sure what else to check...

[uTorrent]
convert = true
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = tv-sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = true
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = ****
password = ****
output_directory = 
radarr-label = radarr

**Comment by mdhiggins** [comment]
Do the directories listed in the logs correspond to where the files are?

It looks like the files are located in 
C:\Users\CaptainWiggles\Videos\Completed\Piper.2016.1080p.BluRay.H264.AAC-RARBG\Piper.2016.1080p.BluRay.H264.AAC-RARBG.mp4 during processing 

but then a different directory is passed

C:\Users\CaptainWiggles\Videos\Torrent_Converted

And the Radarr logs aren’t looping the same thing over and over you can see it’s doing stuff and looks like it finds the file and parses the movie correctly. 

What loops exactly?

**Comment by mdhiggins** [comment]
And webUI doesn’t have anything to do with Radarr. WebUI enables manipulating the state of the torrent inside uTorrent after processing is complete and you need to have that API enabled within uTorrent. That seems likes it’s failing it’s authentication

**Comment by mdhiggins** [comment]
The final entries in the log show Radarr finding the location, determining it’s a movie and determining its quality which looks exactly perfect 

2020-2-22 13:34:06.8|Debug|Parser|Parsing string 'Piper.2016.1080p.BluRay.H264.AAC-RARBG'
2020-2-22 13:34:06.8|Debug|Parser|Movie Parsed. Piper - 2016
2020-2-22 13:34:06.8|Debug|ParsingService|Language(s) parsed:
2020-2-22 13:34:06.8|Debug|QualityParser|Trying to parse quality for A Movie.2016.1080p.BluRay.H264.AAC-RARBG
2020-2-22 13:34:06.8|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)

**Comment by Captain-Wiggles** [comment]
My knowledge of everything had been gained over the past week so I appreciate the help on such basic items. 

I see. My understanding now is that radarr was working perfectly previously (I was misunderstanding the log files) and parsing the information for the movie file as it was registering it as being downloaded. Because my webui file was set to false, then there was no update to radarr and hence no update.

I don't see any "API enable" option on uTorrent. I had assumed that the webui tab was what enabled it. Is this not the case? 

Thanks for the help!

**Comment by mdhiggins** [comment]
WebUI is the API essentially but all that’s gonna do is remove or stop the torrent after things are done from uTorrent. Radarr should still import and rename the file if that’s enabled in Radarr. Was that working?

If the authentication is failing I would verify your credentials in autoProcess and if it’s still failing see if you can post the full error. The script does generate logs in index.log that might be helpful in this regard 

But overall aside from the torrent staying in uTorrent when things are done everything else should be working

**Comment by Captain-Wiggles** [comment]
Ahh, so that means the webui settings can be set to false then? I checked it and it still failed with correct credentials. The logs don't seem to log the crashes (multiple attempts below)

2020-02-22 16:13:27 - uTorrentPostProcess - INFO - uTorrent post processing started.
2020-02-22 16:19:33 - uTorrentPostProcess - INFO - uTorrent post processing started.
2020-02-22 17:12:03 - uTorrentPostProcess - INFO - uTorrent post processing started.
2020-02-22 17:28:42 - uTorrentPostProcess - INFO - uTorrent post processing started.

If this is not required for uTorrent to handoff to Radarr, then I'll just keep it as false for now. 

When "Complete Downloading Handling" is enabled, radarr will import and rename the original file from where uTorrent downloads. I've disabled that and set the drone factory to 0 so its currently not doing so. 

Going back to your original comment, I have uTorrent saving completed files in:
C:\Users\CaptainWiggles\Videos\Completed
While mp4_automator is converting in:
output_directory = C:\Users\CaptainWiggles\Videos\Converted

Is this an issue?

**Comment by mdhiggins** [comment]
Shouldn’t be was just confirming. You don’t need the WebUI stuff that’s all optional. Radarr should be importing after that notification is sent. If WebUI is causing a crash turn that off or it may fail to notify Radarr to initiate the import process.

**Comment by Captain-Wiggles** [comment]
So I cleared the output_directory which resulted in it working. uTorrent now passes it to radarr, radarr then process and relocates the finished file. 

I tested with the output_directory as well just for testing and the radarr couldn't parse the directory then stopped there (no relocate & rename). 

In any case, I'll keep it blank as that seems to be working for me. 

Thanks again for the help!

**Comment by mdhiggins** [comment]
I’m gonna try to add subdirectories to output directory to see if I can get Radarr to recognize those things

**Comment by mdhiggins** [comment]
Just pushed a small update this morning if you want to reenable output_directory and see if radarr picks up the file (specifically for uTorrent)

**Comment by Captain-Wiggles** [comment]
Tested and the result is:
 - file is converted to mkv as per my settings (original file is mp4)
 - radarr parsed movie correctly and lists the movie quality on radarr but is 'missing'
 - movie folder is created in my media hard drive as it should except that it is empty
 - movie file is finally located in output_directory

[autoProcessclean.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4241761/autoProcessclean.txt)

mp4's log file:

2020-02-23 11:38:44 - RadarrPostProcess - INFO - Radarr extra script post processing started.
2020-02-23 11:38:44 - uTorrentPostProcess - INFO - uTorrent post processing started.
2020-02-23 11:38:44 - RadarrPostProcess - INFO - {'TMP': 'C:\\WINDOWS\\TEMP', 'COMPUTERNAME': 'SINKINGSHIP', 'RADARR_ISUPGRADE': 'False', 'RADARR_MOVIEFILE_RELEASEGROUP': 'RARBG', 'USERDOMAIN': 'WORKGROUP', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 23 Stepping 10, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '170a', 'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\FileBot\\;C:\\Python27;C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'TEMP': 'C:\\WINDOWS\\TEMP', 'RADARR_EVENTTYPE': 'Download', 'RADARR_DOWNLOAD_ID': '6337F2B4C8CE39BC1D38FDA58823D2DA05316883', 'RADARR_MOVIEFILE_QUALITYVERSION': '1', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'RADARR_MOVIE_TMDBID': '399106', 'RADARR_MOVIEFILE_SOURCEPATH': 'C:\\Users\\CaptainWiggles\\Videos\\Downloading\\Piper.2016.1080p.BluRay.H264.AAC-RARBG\\Piper.2016.1080p.BluRay.H264.AAC-RARBG.mp4', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local', 'RADARR_MOVIEFILE_ID': '22', 'RADARR_MOVIEFILE_PATH': 'J:\\Plex\\Movies\\Piper (2016)\\Piper (2016) - Bluray-1080p x264 AAC.mp4', 'PROGRAMW6432': 'C:\\Program Files', 'RADARR_MOVIEFILE_SCENENAME': 'Piper.2016.1080p.BluRay.H264.AAC-RARBG', 'USERNAME': 'SINKINGSHIP$', 'RADARR_MOVIEFILE_RELATIVEPATH': 'Piper (2016) - Bluray-1080p x264 AAC.mp4', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'RADARR_MOVIE_ID': '35', 'PROGRAMDATA': 'C:\\ProgramData', 'RADARR_MOVIE_IN_CINEMAS_DATE': '2016-06-16 4:00:00 AM', 'PUBLIC': 'C:\\Users\\Public', 'RUNTIME_VERSION': '4.8.0', 'RADARR_MOVIEFILE_QUALITY': 'Bluray-1080p', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Roaming', 'RADARR_MOVIE_PHYSICAL_RELEASE_DATE': '', 'SYSTEMDRIVE': 'C:', 'RADARR_MOVIE_TITLE': 'Piper', 'RADARR_MOVIE_PATH': 'J:\\Plex\\Movies\\Piper (2016)', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_LEVEL': '6', 'RADARR_MOVIEFILE_SOURCEFOLDER': 'C:\\Users\\CaptainWiggles\\Videos\\Downloading\\Piper.2016.1080p.BluRay.H264.AAC-RARBG', 'RADARR_MOVIE_YEAR': '2016', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'RADARR_MOVIE_IMDBID': 'tt5613056', 'USERPROFILE': 'C:\\WINDOWS\\system32\\config\\systemprofile'}
2020-02-23 11:38:44 - uTorrentPostProcess - INFO - Performing conversion
2020-02-23 11:38:53 - uTorrentPostProcess - INFO - Passing C:\Users\CaptainWiggles\Videos\Completed\Piper.2016.1080p.BluRay.H264.AAC-RARBG directory to Radarr.
2020-02-23 11:38:53 - autoprocess.radarr - INFO - Radarr notifier started.
2020-02-23 11:38:53 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'C:\Users\CaptainWiggles\Videos\Completed\Piper.2016.1080p.BluRay.H264.AAC-RARBG'.
2020-02-23 11:38:54 - RadarrPostProcess - INFO - Processing J:\Plex\Movies\Piper (2016)\Piper (2016) - Bluray-1080p x264 AAC.mp4.
2020-02-23 11:38:55 - autoprocess.radarr - INFO - Radarr response: queued.
2020-02-23 11:39:10 - RadarrPostProcess - INFO - Radarr response: ID 2081 queued.
2020-02-23 11:39:10 - RadarrPostProcess - INFO - Waiting rescan to complete
2020-02-23 11:39:10 - RadarrPostProcess - INFO - started
2020-02-23 11:39:20 - RadarrPostProcess - INFO - Command completed
2020-02-23 11:39:20 - RadarrPostProcess - INFO - Requesting updated information from Radarr for movie ID 35.
2020-02-23 11:39:20 - RadarrPostProcess - INFO - {u'website': u'http://www.pixar.com/short_films/Theatrical-Shorts/Piper', u'overview': u'A mother bird tries to teach her little one how to find food by herself. In the process, she encounters a traumatic experience that she must overcome in order to survive.', u'sizeOnDisk': 0, u'minimumAvailability': u'released', u'year': 2016, u'images': [{u'coverType': u'poster', u'url': u'/MediaCover/35/poster.jpg'}, {u'coverType': u'fanart', u'url': u'/MediaCover/35/fanart.jpg'}], u'id': 35, u'alternativeTitles': [], u'genres': [], u'monitored': True, u'inCinemas': u'2016-06-16T04:00:00Z', u'title': u'Piper', u'tags': [], u'tmdbId': 399106, u'lastInfoSync': u'2020-02-23T16:29:19.4575202Z', u'status': u'released', u'added': u'2020-02-23T16:29:18.5982121Z', u'pathState': u'static', u'imdbId': u'tt5613056', u'cleanTitle': u'piper', u'downloaded': False, u'studio': u'Pixar', u'sortTitle': u'piper', u'path': u'J:\\Plex\\Movies\\Piper (2016)', u'runtime': 6, u'titleSlug': u'piper-399106', u'hasFile': False, u'folderName': u'J:\\Plex\\Movies\\Piper (2016)', u'ratings': {u'votes': 957, u'value': 8.2}, u'qualityProfileId': 1, u'secondaryYearSourceId': 0, u'profileId': 1, u'isAvailable': True, u'youTubeTrailerId': u'Cn5l7HJaYuA'}
2020-02-23 11:39:22 - RadarrPostProcess - INFO - Radarr monitoring information updated for movie Piper.

**Comment by Captain-Wiggles** [comment]
Tested again with output_directory blank. (and different file for faster testing)

- file is converted to mkv as per my settings
- radarr parsed movie correctly, lists the movie quality on radarr, and is 'downloaded
- movie folder is created in my media hard drive 
- movie correctly in placed in movie folder
- temporary file was not deleted and placed in movie folder

[index.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4241850/index.log)

**Comment by mdhiggins** [comment]
I think that’s the intended behavior. What do you mean by temporary file?

**Comment by Captain-Wiggles** [comment]
Gotcha. everything seems to be working fine now then. I had thought that the output_directory was where conversion would occur and then moved with postprocessing but upon some more testing I see that's not the case. 

Two final questions:
After uTorrent completion, the python window opens and lists conversion is in process. Is there anyway to include the progress bar similar to the graphic with manual.py? 
If two downloads finish at the same time, will that cause an issue having two processes occurring simultaneously?

Thanks again.

**Comment by mdhiggins** [comment]
There is a specific output_directory setting for uTorrent (or any of the download clients) that will do what you're looking for converting in a specific location. The main output_dir setting is the one that moves everything at any stage, but if you set at at the specific application level that won't mess up postRadarr/postSonarr

Unfortunately the popup uTorrent creates doesn't support the percentage bar and just won't display it, the code isn't explicitly disabled or anything it just doesn't render

Having 2 running at the same time shouldn't cause any issues

**Comment by Captain-Wiggles** [comment]
Understood. Thanks.

If two downloads complete at the same time, are the conversions queued in series or do they run in parallel?

**Comment by mdhiggins** [comment]
Parallel. UTorrent doesn’t support a queuing system

**Comment by Captain-Wiggles** [comment]
Understood. 

Working a through a few more sample files I have another curiosity. On final files, I am getting 2 AAC audio files in my MKVs. I'm suspecting it having to do with the MOOV atom setting as the removed file will be fine and the deleted translated file is actually correct with the only one AAC. Is this due to the file extension being MKV?

**Comment by mdhiggins** [comment]
Nah nothing to do with the moov atom setting

Probably has everything to do with the iOS-audio setting and process-same-extension

- `ios-audio` = creates a 2nd copy of an audio stream that will be stereo and a different more compatible format if the normal output will not be. If a stereo source stream is detected with this option enabled, only one output stream will be produced in this codec to avoid multiple stereo audio stream copies in different codecs. True defaults to AAC, you may also set this option to a specific codec to override the default. Not specifically for iOS but legacy naming
- `process-same-extensions` = instructs the script to reprocess and convert files even if they are already in the same format Good if you have old files that you want to match your current codec configuration. In situations where it looks like all streams are already correct (all streams being copied, no encoding) conversion will still be skipped. **Caution: Set ios-audio to False when reprocessing files to avoid adding multiple iOS audio streams**

You can either disbale this feature or only have conversion enabled at the postRadarr/postSonarr level instead of at the downloader level (utorernt, deluge, SAB, NZBGet etc)

**Comment by Captain-Wiggles** [comment]
I've had the ios-audio settings set to false and tested it on a few movies and it still doubles the AAC audio. My guess now is that it's due to the "audio-copy-original" setting set to be true paired with utorrents "convert" set to true.

Will further test and update.

**Comment by mdhiggins** [comment]
Yeah that will do it as well. Turn one of those options off and you should be good

**Comment by mdhiggins** [comment]
Updated the readme to reflect this
98d35f431808b6b8554473ff345d68f95986f2a9
