### ISSUE TITLE
Path to script folder appears to be invalid

### ISSUE THREAD

**Issue by thamilton91** [mdhiggins/sickbeard_mp4_automator#351]
I posted about this once before.

Recently the converter suddenly stopped working with CouchPotato and i'm receiving this message:

10-22 14:46:24ERROR[              PostProcess] Path to script folder appears to be invalid.

I have the script located in Applications under a folder "mp4_automator" - so in the main.py of for custom_plugins i have the path set as "/Applcations/mp4_automator/"

Not sure what happened or what i'm doing wrong.
![screen shot 2015-10-22 at 2 50 40 pm](https://cloud.githubusercontent.com/assets/5624324/10675106/589d9e62-78cc-11e5-9c43-d6712c9932b1.png)
![screen shot 2015-10-22 at 2 51 02 pm](https://cloud.githubusercontent.com/assets/5624324/10675110/5e725d78-78cc-11e5-8a66-036fea34e7fa.png)

**Comment by mdhiggins** [comment]
I actually just overhauled the main.py file and incorporated some updates to the script that fixes this. It's a problem that developed due to switching over to using pip packages. I actually pushed the update like 5 minutes before I saw your issue haha

Just update your script and main.py file in the custom_plugin directory (remember you have to shut down couch potato, delete main.py and main.pyc, update with the new version, then relaunch).

Let me know if its resolved after updating.

**Comment by mdhiggins** [comment]
491d29aedd72403825cc6b56ffd7fa134578280f

**Comment by thamilton91** [comment]
After the update, that issue has been resolved.

it appears though that the MKV is not converting to MP4, no error is being thrown, but nothing is actually happening on the backend.
![screen shot 2015-10-22 at 5 25 19 pm](https://cloud.githubusercontent.com/assets/5624324/10678706/0d3787ec-78e2-11e5-9e75-3592eca4b807.png)

**Comment by mdhiggins** [comment]
Can you check the info.log file in the script directory and see if theres any references to CouchPotatoPostConversion that are being called? Or any relevant errors? The new change shifts most of the logging away from couchpotato and back to the internal logging of the script.

**Comment by mdhiggins** [comment]
Did some testing on my macbook and I found some problems that weren't occuring on my initial test machine (Windows). Just pushed a new update that I think should address the problem. You will however need to go through the update process again, as it was a change to the main.py file (shutdown CP, delete main.py and main.pyc, replace, restart CP). Give it a try and let me know.

**Comment by thamilton91** [comment]
it does not appear to be logging anything specifically for CouchPotato.

I removed the log file, relaunched CouchPotato, the file moves, the script is found, but no log file is generated.

**Comment by mdhiggins** [comment]
See my last post I made just a few seconds ago ^

The issue was the postCouchPotato.py wasn't being executed due to certain issues under OSX/Linux (using Shell=True and permissions problems). Update and try again if you could.

**Comment by thamilton91** [comment]
No change here, PostProcess still executes, but file is still not converting to MP4.

info.log is also still not being generated either.

![screen shot 2015-10-23 at 9 07 13 pm](https://cloud.githubusercontent.com/assets/5624324/10708079/39810aa6-79ca-11e5-97df-2245c42ffa1c.png)

**Comment by mdhiggins** [comment]
Can you post your main.py script like you did before? Just wanna make sure nothing is wrong there

**Comment by thamilton91** [comment]
![screen shot 2015-10-23 at 9 20 50 pm](https://cloud.githubusercontent.com/assets/5624324/10708132/f994c3ea-79cb-11e5-8ec3-2550aaa3b202.png)

**Comment by mdhiggins** [comment]
I guess next I would double check your permissions on postCouchPotato.py and make sure it has execute permissions. If that doesn't work I'll write up a debugging script that will help figure out why its not able to execute hopefully

**Comment by mdhiggins** [comment]
Also just make sure that when you launch manual.py you're not getting any errors/problems

**Comment by thamilton91** [comment]
I did a fresh install of OS X on another machine and installed only CouchPotato and this script, I'm seeing the same problem.

All permissions are set to execute across the board and Manual.py runs without issue.

![screen shot 2015-10-23 at 11 03 11 pm](https://cloud.githubusercontent.com/assets/5624324/10708538/67c09232-79da-11e5-87c9-62b386b57218.png)

**Comment by mdhiggins** [comment]
Here's a modified version of main.py with some more debugging that should help figure out what's going on:

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
import traceback
import os
import subprocess

log = CPLog(__name__)

# Edit to point to the absolute path where the rest of the script resides
path = "C:\\Scripts\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)


    def callscript(self, message = None, group = None):

        log.info('MP4 Automator - Post processing script initialized')

        exec_me = os.path.join(path, "postCouchPotato.py")

        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]

        success = True

        for inputfile in moviefile:
            try:
                log.info("Executing post processing on file %s" % inputfile)
                process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=(os.name=='nt'), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=None)
                while True:
                    output = process.stdout.readline()
                    if output == '' and process.poll() is not None:
                        break
                    if output:
                        log.info(output.strip())
                    rc = process.poll()
            except:
                log.error("Failed to execute post processing on file %s" % inputfile)
                log.error(traceback.format_exc())
                success = False

        return success
```

**Comment by thamilton91** [comment]
Heres the CouchPotato log with the modified main.py.

![screen shot 2015-10-26 at 7 14 07 pm](https://cloud.githubusercontent.com/assets/5624324/10745174/d62cdd9c-7c15-11e5-8b63-f2b29f3efaa2.png)

**Comment by mdhiggins** [comment]
Looks like when I pasted that into the comment I screwed up the tab for the final return line, so that error you got isn't helpful. My bad. Here is the correct code that will hopefully produce a more meaningful error messages. Sorry you have to go through it all again

```
from couchpotato.core.event import addEvent
from couchpotato.core.logger import CPLog
from couchpotato.core.plugins.base import Plugin
import traceback
import os
import subprocess

log = CPLog(__name__)

# Edit to point to the absolute path where the rest of the script resides
path = "C:\\Scripts\\"


class PostProcess(Plugin):

    def __init__(self):
        addEvent('renamer.after', self.callscript)


    def callscript(self, message = None, group = None):

        log.info('MP4 Automator - Post processing script initialized')

        exec_me = os.path.join(path, "postCouchPotato.py")

        try:
            imdbid = group['library']['identifier']
        except:
            imdbid = group['identifier']

        moviefile = group['renamed_files']
        original = group['files']['movie'][0]

        success = True

        for inputfile in moviefile:
            try:
                log.info("Executing post processing on file %s" % inputfile)
                process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=(os.name=='nt'), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=None)
                while True:
                    output = process.stdout.readline()
                    if output == '' and process.poll() is not None:
                        break
                    if output:
                        log.info(output.strip())
                    rc = process.poll()
            except:
                log.error("Failed to execute post processing on file %s" % inputfile)
                log.error(traceback.format_exc())
                success = False

            return success
```

**Comment by thamilton91** [comment]
![screen shot 2015-10-27 at 1 05 06 am](https://cloud.githubusercontent.com/assets/5624324/10749986/c7d43b6a-7c46-11e5-8231-22f3c3cf647e.png)

**Comment by mdhiggins** [comment]
Looks like you're still having indentation problems, maybe your text editor isn't handling things properly.

I just uploaded a copy to my dropbox, download and use this main.py file instead

https://www.dropbox.com/s/hlc32hq0qkvbqaf/main.py?dl=0

**Comment by thamilton91** [comment]
![screen shot 2015-10-27 at 1 18 46 am](https://cloud.githubusercontent.com/assets/5624324/10750188/c33a8d46-7c48-11e5-81d2-3376e4ae3e81.png)

**Comment by mdhiggins** [comment]
Hm so that fixed the syntax errors but didn't provide any additional information like it should have. I was hoping we'd get some output from the script indicating an importerror or something pythonic in nature causing the problem, but it looks like its not even getting that far.

Just wrote another custom main.py that may give us more info, this is turning out to be challenging to solve, I apologize.

Here is the new one:
https://www.dropbox.com/s/hlc32hq0qkvbqaf/main.py?dl=0

**Comment by thamilton91** [comment]
It's no problem, appreciate the support!

![screen shot 2015-10-27 at 3 24 56 pm](https://cloud.githubusercontent.com/assets/5624324/10769932/09119028-7cbf-11e5-9751-847c673b1d21.png)

**Comment by mdhiggins** [comment]
Looks like it's erroring out because babelfish isn't installed. Try running `pip install babelfish` and see where that gets you. If babelfish is already installed we'll have to further investigate.

**Comment by thamilton91** [comment]
Looks like it's already installed and up to date.

![screen shot 2015-10-27 at 10 48 42 pm](https://cloud.githubusercontent.com/assets/5624324/10778456/eeb20274-7cfc-11e5-96e6-a07840b3922b.png)

**Comment by mdhiggins** [comment]
I'm wondering if Python is being run in an isolated environment where babelfish isn't installed? I'm not sure what would cause this honestly. Maybe uninstall and reinstall babelfish.

**Comment by thamilton91** [comment]
is babelfish supposed to be located within the script folder? because it isn't.

**Comment by thamilton91** [comment]
if i put a copy of babelfish within the script folder i receive this error.

![screen shot 2015-10-28 at 12 02 49 am](https://cloud.githubusercontent.com/assets/5624324/10779445/4e7851f4-7d07-11e5-9eec-86f3c9b761c2.png)

**Comment by mdhiggins** [comment]
Babelfish shouldn't be located in the script folder, it should be a module installed via PIP, I suspect that for some reason the version of python being executed by CouchPotato to kick off the processing is failing because its running in a different python environment than where all your required modules are installed. Not sure why that is exactly but I'm looking into it.

**Comment by mdhiggins** [comment]
I whipped up another main.py file, give it a try:
https://www.dropbox.com/s/hlc32hq0qkvbqaf/main.py?dl=0

The problem is that python scripts executed under CouchPotato use a different pythonpath and therefore don't have all the preinstalled packages that the script requires. I'm not able to reproduce this problem on my Mac though. The other thing I want you to try, at least if that main.py script doesn't work, is the following:

1. open up terminal
2. run `/usr/bin/env python` which should bring up a python terminal
3. type `import babelfish` and see if you get an error or if it is successful
4. if you get an error, type `import sys` and then `print(sys.path)` and send me the output

**Comment by thamilton91** [comment]
No errors on import babelfish.

also looks like I'm getting the same babelfish error with the new main.py - any suggestions of something else to try? What version of OS X are you running?

![screen shot 2015-10-28 at 12 02 49 am](https://cloud.githubusercontent.com/assets/5624324/10798854/047de98c-7d80-11e5-9a72-e262e9bbe0b7.png)

**Comment by mdhiggins** [comment]
You'll need to delete that version of babelfish you put in your script directory.

Also try opening up terminal and running `export PYTHONPATH` and then retesting with CP.

I'm running El Capitan.

**Comment by mdhiggins** [comment]
The other option if we can't get this sorted is to run CouchPotato from source rather than the precompiled binary, which I think would resolve the issue since it would all be under the one python environment.

**Comment by mdhiggins** [comment]
Good news! I believe I have fixed the issue. I was finally able to replicate the problem which sped up my ability to debug and try things very quickly.

Just pushed a new change to the master build with a new main.py in the setup folder.

The problem was being created because CouchPotato, which runs in an isolated python environment separate from the main environment where all the dependent packages have been installed, was passing its environment to the new instance that was supposed to be created. This prevented the script from accessing all its dependencies since it was still trapped in the couch potato environment. This problem only happens on OSX and only when using CouchPotato as a compiled application, not when running from source, which is why it took me forever to replicate the problem. The new update blocks the environment from being passed and the default environment is launched instead, fixing everything.

Give it a test and let me know if its working. All seems well on my end.

**Comment by thamilton91** [comment]
Installed new version of script, receiving these errors now.

![screen shot 2015-10-28 at 5 28 34 pm](https://cloud.githubusercontent.com/assets/5624324/10803615/74b2f166-7d99-11e5-9dc1-8c6fa0405985.png)

**Comment by mdhiggins** [comment]
Did you remember to modified the path variable in the new main.py file?

**Comment by thamilton91** [comment]
whoops, sorry about that.

looks like I'm still getting the babelfish error though.

![screen shot 2015-10-28 at 5 47 57 pm](https://cloud.githubusercontent.com/assets/5624324/10804103/16b2e7f8-7d9c-11e5-895a-c81b335ffb5d.png)

**Comment by mdhiggins** [comment]
Damn, I really thought that would do it, any way I can just remote into your machine and test? Cause now I have no idea why its not working lol

**Comment by thamilton91** [comment]
I actually installed OS X to an external drive and installed only this script and couch potato, the post processing functions fine.

I think i'm just going to clean install my internal drive and see how that goes.

Thanks again!

**Comment by mdhiggins** [comment]
Ah nice, so you’re having at least some success with the latest changes then, that’s good. Let me know if you’re able to get it running on your main setup, but I think its solved. My only other thought is that maybe things are being installed under a virtualenv on your main box and that’s creating problems, but at this point I think that’s less likely. But keep me posted so we can close out this issue.

**Comment by thamilton91** [comment]
looks like we're all good! thanks again for all the support.

![screen shot 2015-10-29 at 12 24 12 pm](https://cloud.githubusercontent.com/assets/5624324/10824763/225a8452-7e38-11e5-9903-cec43b6a62b2.png)

**Comment by mdhiggins** [comment]
Excellent! Closing this out
