### ISSUE TITLE
postSonarr.py Permission not set to Executable

### ISSUE THREAD

**Issue by Smithoo4** [mdhiggins/sickbeard_mp4_automator#385]
I have been trying Sonarr for the first time and I have noted that postSonarr.py script's permission is not set to be executable. I am running this on an Arch linux box.  It is also worth noting is that postConversion.py and postCouchPotato.py are set to be executable.

This is not a big deal as it is easy to correct after downloading. But it would be nice to see this corrected upstream for other Linux users.

Cheers

**Comment by mdhiggins** [comment]
Should be fixed, thanks for pointing this out

**Comment by Smithoo4** [comment]
First of all thank you for your fast responses; it is very much appreciated.

However, I just did a fresh “git clone https://github.com/mdhiggins/sickbeard_mp4_automator.git” and the permission of postSonarr.py is still not set to be executable. Its permission is not the same as PostConversion.py and postCouchPotato.py; please see the output of ls -l for the directory below.

I don't believe I am doing something wrong, but if I am please point it out.

Cheers 

drwxr-xr-x 2 morgan users   128 Dec 29 22:06 autoprocess
-rw-r--r-- 1 morgan users  1818 Dec 29 22:06 autoProcess.ini.sample
drwxr-xr-x 2 morgan users    75 Dec 29 22:06 converter
-rw-r--r-- 1 morgan users    43 Dec 29 22:06 delugePostProcess.bat
-rw-r--r-- 1 morgan users  4101 Dec 29 22:06 delugePostProcess.py
-rw-r--r-- 1 morgan users   624 Dec 29 22:06 extensions.py
-rw-r--r-- 1 morgan users     0 Dec 29 22:06 __init__.py
-rw-r--r-- 1 morgan users  4566 Dec 29 22:06 installffmpeg.sh
-rw-r--r-- 1 morgan users  1122 Dec 29 22:06 logging.ini
-rwxr-xr-x 1 morgan users 14709 Dec 29 22:06 manual.py
-rw-r--r-- 1 morgan users 32917 Dec 29 22:06 mkvtomp4.py
drwxr-xr-x 3 morgan users   146 Dec 29 22:06 mutagen
-rwxr-xr-x 1 morgan users  7867 Dec 29 22:06 NZBGetPostProcess.py
-rwxr-xr-x 1 morgan users  2600 Dec 29 22:06 postConversion.py
-rwxr-xr-x 1 morgan users  2053 Dec 29 22:06 postCouchPotato.py
drwxr-xr-x 3 morgan users    71 Dec 29 22:06 post_process
-rw-r--r-- 1 morgan users  2564 Dec 29 22:06 post_processor.py
-rw-r--r-- 1 morgan users  2254 Dec 29 22:06 postSonarr.py
-rw-r--r-- 1 morgan users 28950 Dec 29 22:06 README.md
-rw-r--r-- 1 morgan users 26522 Dec 29 22:06 readSettings.py
-rw-r--r-- 1 morgan users  3114 Dec 29 22:06 SABPostProcess.py
drwxr-xr-x 3 morgan users    60 Dec 29 22:06 setup
drwxr-xr-x 2 morgan users    38 Dec 29 22:06 tmdb_api
-rw-r--r-- 1 morgan users  7985 Dec 29 22:06 tmdb_mp4.py
drwxr-xr-x 2 morgan users   104 Dec 29 22:06 tvdb_api
-rwxr-xr-x 1 morgan users 11352 Dec 29 22:06 tvdb_mp4.py
-rw-r--r-- 1 morgan users  7646 Dec 29 22:06 uTorrentPostProcess.py

**Comment by mdhiggins** [comment]
Hm somehow I screwed that up. Just pushed another commit, lemme know if its working now

**Comment by Smithoo4** [comment]
Looks good to me,

Thank you
