### ISSUE TITLE
Sonarr not processing converted file

### ISSUE THREAD

**Issue by ikrowni** [mdhiggins/sickbeard_mp4_automator#758]
Just got all setup and have my files converting properly now. But when the conversion finishes sonarr isnt moving the file to the proper place.

```
2017-07-06 20:22:42 - uTorrentPostProcess - INFO - uTorrent post processing started.
2017-07-06 20:22:42 - readSettings - INFO - C:\Python27\python.exe
2017-07-06 20:22:42 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_idnumber = guessit.transfo.guess_idnumber:GuessIdnumber')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_bonus_features = guessit.transfo.guess_bonus_features:GuessBonusFeatures')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_date = guessit.transfo.guess_date:GuessDate')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('expected_title = guessit.transfo.expected_title:ExpectedTitle')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('expected_series = guessit.transfo.expected_series:ExpectedSeries')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_path_components = guessit.transfo.split_path_components:SplitPathComponents')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_properties = guessit.transfo.guess_properties:GuessProperties')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_release_group = guessit.transfo.guess_release_group:GuessReleaseGroup')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_explicit_groups = guessit.transfo.split_explicit_groups:SplitExplicitGroups')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episode_details = guessit.transfo.guess_episode_details:GuessEpisodeDetails')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episodes_rexps = guessit.transfo.guess_episodes_rexps:GuessEpisodesRexps')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_weak_episodes_rexps = guessit.transfo.guess_weak_episodes_rexps:GuessWeakEpisodesRexps')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episode_info_from_position = guessit.transfo.guess_episode_info_from_position:GuessEpisodeInfoFromPosition')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_on_dash = guessit.transfo.split_on_dash:SplitOnDash')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_movie_title_from_position = guessit.transfo.guess_movie_title_from_position:GuessMovieTitleFromPosition')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_video_rexps = guessit.transfo.guess_video_rexps:GuessVideoRexps')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_country = guessit.transfo.guess_country:GuessCountry')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_language = guessit.transfo.guess_language:GuessLanguage')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_website = guessit.transfo.guess_website:GuessWebsite')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_year = guessit.transfo.guess_year:GuessYear')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_filetype = guessit.transfo.guess_filetype:GuessFiletype')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('podnapisi = subliminal.providers.podnapisi:PodnapisiProvider')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('opensubtitles = subliminal.providers.opensubtitles:OpenSubtitlesProvider')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('addic7ed = subliminal.providers.addic7ed:Addic7edProvider')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('subscenter = subliminal.providers.subscenter:SubsCenterProvider')
2017-07-06 20:22:42 - stevedore.extension - DEBUG - found extension EntryPoint.parse('thesubdb = subliminal.providers.thesubdb:TheSubDBProvider')
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Path: Z:\Downloads\___TORRENTS___\sonarr.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Label: sonarr.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Categories: ['couchpotato', 'sickbeard', 'sonarr', 'radarr', 'sickrage', 'bypass'].
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Torrent hash: E66FC82D13691F0621D25B6C63C4EB38BE4BBDE5.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Torrent name: Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - WebUI is true.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Request sent successfully - Before Function.
2017-07-06 20:22:42 - uTorrentPostProcess - DEBUG - Sending action stop to uTorrent
2017-07-06 20:22:42 - uTorrentPostProcess - INFO - Performing conversion
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Settings imported.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Settings imported.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv is valid.
2017-07-06 20:22:42 - uTorrentPostProcess - INFO - Processing file Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Process started.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv is valid.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv needs processing.
2017-07-06 20:22:42 - mkvtomp4 - INFO - Reading video stream.
2017-07-06 20:22:42 - mkvtomp4 - INFO - Video codec detected: h264.
2017-07-06 20:22:42 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Video codec: copy.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Video bitrate: 577.359.
2017-07-06 20:22:42 - mkvtomp4 - INFO - Reading audio streams.
2017-07-06 20:22:42 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2017-07-06 20:22:42 - mkvtomp4 - INFO - Audio detected for stream #1: aac [und].
2017-07-06 20:22:42 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Overriding default channel settings because iOS audio is enabled but the source is stereo [iOS-audio].
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Audio codec: copy.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Channels: 2.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Bitrate: 256.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Language: und
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Filter: None
2017-07-06 20:22:42 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to default
2017-07-06 20:22:42 - mkvtomp4 - INFO - Reading subtitle streams.
2017-07-06 20:22:42 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2017-07-06 20:22:42 - mkvtomp4 - INFO - {
    "preopts": [], 
    "subtitle": {}, 
    "format": "mp4", 
    "postopts": [
        "-threads", 
        "auto"
    ], 
    "video": {
        "map": 0, 
        "codec": "copy", 
        "bitrate": 577.359, 
        "level": null
    }, 
    "audio": {
        "0": {
            "map": 1, 
            "language": "und", 
            "channels": 2, 
            "codec": "copy", 
            "disposition": "default", 
            "bitrate": 256, 
            "filter": null
        }
    }
}
2017-07-06 20:22:42 - mkvtomp4 - INFO - Starting conversion.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Input directory: Z:\Downloads\___TORRENTS___\sonarr.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - File name: Family.Guy.S15E20.HDTV.x264-SVA[eztv].
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Input extension: mkv.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Output directory: Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert.
2017-07-06 20:22:42 - mkvtomp4 - DEBUG - Output file: Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mp4.
2017-07-06 20:22:43 - mkvtomp4 - INFO - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mp4 created.
2017-07-06 20:22:43 - mkvtomp4 - DEBUG - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mp4 created from Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv successfully.
2017-07-06 20:22:43 - mkvtomp4 - DEBUG - Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mp4 is valid.
2017-07-06 20:22:43 - mkvtomp4 - DEBUG - Height: 404
2017-07-06 20:22:43 - mkvtomp4 - DEBUG - Width: 720
2017-07-06 20:22:43 - uTorrentPostProcess - INFO - Passing Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert directory to Sonarr.
2017-07-06 20:22:43 - autoprocess.sonarr - INFO - Sonarr notifier started.
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - Sonarr host: localhost.
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - Sonarr port: 8092.
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - Sonarr webroot: .
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - Sonarr apikey: SECRET.
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - Sonarr protocol: http://.
2017-07-06 20:22:43 - autoprocess.sonarr - DEBUG - URL 'http://localhost:8092/api/command' with payload '{'path': 'Z:\\Downloads\\___TORRENTS___\\sonarr\\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert', 'name': 'downloadedepisodesscan'}.'
2017-07-06 20:22:43 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'Z:\Downloads\___TORRENTS___\sonarr\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert'.
2017-07-06 20:22:43 - autoprocess.sonarr - INFO - Sonarr response: queued.
2017-07-06 20:22:43 - uTorrentPostProcess - DEBUG - Request sent successfully - After Function.
2017-07-06 20:22:43 - uTorrentPostProcess - DEBUG - Sending action removedata to uTorrent
2017-07-06 20:22:43 - uTorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\uTorrentPostProcess.py", line 194, in <module>
    os.rmdir(delete_dir)
WindowsError: [Error 145] The directory is not empty: 'Z:\\Downloads\\___TORRENTS___\\sonarr\\Family.Guy.S15E20.HDTV.x264-SVA[eztv].mkv-convert'
```

I found this [issue#336](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/336) But it says the problem was resolved.

**Comment by mdhiggins** [comment]
Perhaps related to this?
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/743

**Comment by ozdrummerboy** [comment]
Not sure if its related but I have a somewhat similar issue. For me it is related to the "output_directory" parameter being set under the [MP4] section of the autoprocess.ini config file. If I don't set this directory, sonarr moves and renames the file as expected but when the output directory is set, the file is not moved/renamed.  The MP4 conversion happens no problems and the converted file is present in the "output_directory" location.
I am downloading with uTorrent.

Note - I originally set the output directory due to some torrents having a filename of 100 characters long. When the "-convert" directory was added, this pushed the entire path over the windows path limit of 260 characters.

Sickbeard_mp4_automator Log:
2017-08-05 17:45:47 - uTorrentPostProcess - INFO - uTorrent post processing started.
2017-08-05 17:45:47 - readSettings - INFO - C:\Program Files (x86)\Python\python.exe
2017-08-05 17:45:47 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Path: D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Label: sonarr.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Categories: ['couchpotato', 'sickbeard', 'sonarr', 'radarr', 'sickrage', 'bypass'].
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Torrent hash: 10F302C5E023771B4D268D8EE692AF6807343537.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Torrent name: Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - WebUI is true.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Request sent successfully - Before Function.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Sending action stop to uTorrent
2017-08-05 17:45:47 - uTorrentPostProcess - INFO - Performing conversion
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - Settings imported.
2017-08-05 17:45:47 - uTorrentPostProcess - DEBUG - Processing multiple files.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - Settings imported.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4 is valid.
2017-08-05 17:45:47 - uTorrentPostProcess - INFO - Processing file D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - Process started.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4 is valid.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4 does not need processing.
2017-08-05 17:45:47 - mkvtomp4 - DEBUG - Outputfile set to D:\Downloads\Convert\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4.
2017-08-05 17:45:48 - mkvtomp4 - DEBUG - D:\Downloads\Convert\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv].mp4 is valid.
2017-08-05 17:45:53 - mkvtomp4 - DEBUG - Height: 404
2017-08-05 17:45:53 - mkvtomp4 - DEBUG - Width: 720
2017-08-05 17:45:53 - mkvtomp4 - DEBUG - Settings imported.
2017-08-05 17:45:53 - mkvtomp4 - DEBUG - D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt is invalid with extension txt.
2017-08-05 17:45:53 - uTorrentPostProcess - DEBUG - Ignoring file D:\Downloads\Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]\Torrent-Downloaded-from-ExtraTorrent.cc.txt.
2017-08-05 17:45:53 - uTorrentPostProcess - INFO - Passing D:\Downloads\Convert directory to Sonarr.
2017-08-05 17:45:53 - autoprocess.sonarr - INFO - Sonarr notifier started.
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - Sonarr host: localhost.
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - Sonarr port: 8989.
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - Sonarr webroot: .
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - Sonarr apikey: a2076468135341c4a49e9adf472cbdc8.
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - Sonarr protocol: http://.
2017-08-05 17:45:53 - autoprocess.sonarr - DEBUG - URL 'http://localhost:8989/api/command' with payload '{'path': 'D:\\Downloads\\Convert', 'name': 'downloadedepisodesscan'}.'
2017-08-05 17:45:53 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\Convert'.
2017-08-05 17:45:53 - autoprocess.sonarr - INFO - Sonarr response: queued.
2017-08-05 17:45:53 - uTorrentPostProcess - DEBUG - Request sent successfully - After Function.
2017-08-05 17:45:53 - uTorrentPostProcess - DEBUG - Sending action removedata to uTorrent

**Comment by mdhiggins** [comment]
From the logs it looks like everything is working, the Sonarr payload is sent as expected and the path is referenced in the payload (`D:\Downloads\Convert`)
Anything on the Sonarr logs when this command is sent that indicate it was received? And just to confirm you've turned off "completed download handling" in Sonarr which wont work since you're moving out of the default directory?

Also, while it would be nice to sort out why this isn't working, I just pushed a commit that should address the 260 character limit issue for uTorrent/deluge appending either `-convert` or `-copy` to the directory
b09b809726a07a317e29a2a58e22d042a1bfed9e
Let me know

**Comment by ozdrummerboy** [comment]
Confirming  "completed download handling" is turned off.
I have had a look through the Sonarr debug logs and I have attached, the two log files, one with the output directory not set - working, and the other with the output directory set - not working.

The issue appears to be Sonarr is trying to parse `"Convert"` for the episode title - part of my `"output_directory"`, rather than the filename.

Output directory set to `D:\Downloads\Convert`

```
17-8-6 13:56:47.0|Debug|Parser|Parsing string 'Convert'
17-8-6 13:56:47.0|Debug|Parser|Unable to parse Convert
17-8-6 13:56:47.0|Debug|DownloadedEpisodesImportService|Unknown Series Convert
```

No Output Directory Set - 
```
17-8-6 13:28:19.2|Debug|Parser|Parsing string 'Better.Call.Saul.S03E02.WEB-DL.x264-FUM[ettv]-convert'
17-8-6 13:28:19.2|Debug|Parser|Episode Parsed. Better Call Saul - S03E02 
```

I will checkout the commit you pushed regarding the 260 char limit.
Just as a bit of additional information, the issue I had comes more so from torrents that have multiple files in the download so the path of;
`D:\Download\TORRENT_NAME\TORRENT_NAME.mkv`  - becomes
`D:\Download\TORRENT_NAME\TORRENT_NAME-convert\TORRENT_NAME.mp4`

when the torrent name is something like `SHOWNAME_EPISODE_EPISODENAME_LANGUAGE_AUDIOTYPE_RELEASEGROUP_ETC_ETC` it breaks the 260 char limit.
[sonarr.debug (op dir set).txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1202860/sonarr.debug.op.dir.set.txt)
[sonarr.debug(no op dir).txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1202861/sonarr.debug.no.op.dir.txt)

**Comment by ozdrummerboy** [comment]
No luck with https://github.com/mdhiggins/sickbeard_mp4_automator/commit/b09b809726a07a317e29a2a58e22d042a1bfed9e
Still the same issue. Log below. Ive run the FFMpeg command on the command line and I have the same issue until I manually shorten the file references and relocate in the input file accordingly.

```
2017-08-06 15:34:55 - uTorrentPostProcess - INFO - uTorrent post processing started.
2017-08-06 15:34:55 - readSettings - INFO - C:\Program Files (x86)\Python\python.exe
2017-08-06 15:34:55 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2017-08-06 15:34:55 - uTorrentPostProcess - INFO - Performing conversion
2017-08-06 15:34:55 - uTorrentPostProcess - INFO - Processing file D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mkv.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Reading video stream.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Video codec detected: h264.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Reading audio streams.
2017-08-06 15:34:57 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Audio detected for stream #1: eac3 [eng].
2017-08-06 15:34:57 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2017-08-06 15:34:57 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2017-08-06 15:34:57 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2017-08-06 15:34:57 - mkvtomp4 - INFO - Reading subtitle streams.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2017-08-06 15:34:57 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2017-08-06 15:34:57 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2017-08-06 15:34:57 - mkvtomp4 - INFO - Starting conversion.
2017-08-06 15:34:58 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sickbeard MP4 Automator\mkvtomp4.py", line 694, in convert
    for timecode in conv:
  File "C:\Program Files (x86)\Sickbeard MP4 Automator\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\Program Files (x86)\Sickbeard MP4 Automator\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=5988, cmd="C:\Program Files\FFMpeg\bin\ffmpeg.exe -fix_sub_duration -i D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -f mp4 -threads auto -y D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mp4">
2017-08-06 15:34:58 - mkvtomp4 - ERROR - C:\Program Files\FFMpeg\bin\ffmpeg.exe -fix_sub_duration -i D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -f mp4 -threads auto -y D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mp4
2017-08-06 15:34:58 - mkvtomp4 - ERROR - ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 7.1.0 (GCC)

  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib

  libavutil      55. 58.100 / 55. 58.100

  libavcodec     57. 89.100 / 57. 89.100

  libavformat    57. 71.100 / 57. 71.100

  libavdevice    57.  6.100 / 57.  6.100

  libavfilter     6. 82.100 /  6. 82.100

  libswscale      4.  6.100 /  4.  6.100

  libswresample   2.  7.100 /  2.  7.100

  libpostproc    54.  5.100 / 54.  5.100

Input #0, matroska,webm, from 'D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mkv':

  Metadata:

    encoder         : libebml v1.3.4 + libmatroska v1.4.5

    creation_time   : 2017-07-17T02:38:44.000000Z

  Duration: 01:01:27.99, start: 0.000000, bitrate: 8165 kb/s

    Chapter #0:0: start 0.000000, end 2.327000

    Metadata:

      title           : TV Rating

    Chapter #0:1: start 2.327000, end 148.327000

    Metadata:

      title           : Previously On

    Chapter #0:2: start 148.327000, end 153.327000

    Metadata:

      title           : Studio Logo

    Chapter #0:3: start 153.327000, end 386.327000

    Metadata:

      title           : Walder Frey holds a feast for his family; The Twins

    Chapter #0:4: start 386.327000, end 493.327000

    Metadata:

      title           : Opening Credits

    Chapter #0:5: start 493.327000, end 700.327000

    Metadata:

      title           : Bran and Meera arrive at the Wall; The Wall

    Chapter #0:6: start 700.327000, end 1000.327000

    Metadata:

      title           : Jon prepares his men for the coming Winter; Winterfell

    Chapter #0:7: start 1000.327000, end 1170.327000

    Metadata:

      title           : Jon receives a message from King's Landing; Winterfell

    Chapter #0:8: start 1170.327000, end 1508.327000

    Metadata:

      title           : Jaime tells Cersei they need allies; King's Landing

    Chapter #0:9: start 1508.327000, end 1746.327000

    Metadata:

      title           : Euron makes Cersei an offer; King's Landing

    Chapter #0:10: start 1746.327000, end 2159.327000

    Metadata:

      title           : Sam talks with Archmaester Marwyn about the White Walkers; Oldtown

    Chapter #0:11: start 2159.327000, end 2287.327000

    Metadata:

      title           : Littlefinger asks Sansa if she is happy; Winterfell

    Chapter #0:12: start 2287.327000, end 2536.327000

    Metadata:

      title           : Arya runs into a group of soldiers; The Riverlands

    Chapter #0:13: start 2536.327000, end 3091.327000

    Metadata:

      title           : The Brotherhood Without Banners travel north; The North

    Chapter #0:14: start 3091.327000, end 3250.327000

    Metadata:

      title           : Sam discovers something in a book; Oldtown

    Chapter #0:15: start 3250.327000, end 3586.327000

    Metadata:

      title           : Daenerys comes home; Dragonstone

    Chapter #0:16: start 3586.327000, end 3664.327000

    Metadata:

      title           : End Credits

    Chapter #0:17: start 3664.327000, end 3684.327000

    Metadata:

      title           : Next On

    Chapter #0:18: start 3684.327000, end 3687.991000

    Metadata:

      title           : Online Extra

    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

    Metadata:

      BPS             : 7523508

      BPS-eng         : 7523508

      DURATION        : 01:01:27.976000000

      DURATION-eng    : 01:01:27.976000000

      NUMBER_OF_FRAMES: 88423

      NUMBER_OF_FRAMES-eng: 88423

      NUMBER_OF_BYTES : 3468314771

      NUMBER_OF_BYTES-eng: 3468314771

      _STATISTICS_WRITING_APP: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_APP-eng: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_DATE_UTC: 2017-07-17 02:38:44

      _STATISTICS_WRITING_DATE_UTC-eng: 2017-07-17 02:38:44

      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)

    Metadata:

      BPS             : 640000

      BPS-eng         : 640000

      DURATION        : 01:01:27.968000000

      DURATION-eng    : 01:01:27.968000000

      NUMBER_OF_FRAMES: 115249

      NUMBER_OF_FRAMES-eng: 115249

      NUMBER_OF_BYTES : 295037440

      NUMBER_OF_BYTES-eng: 295037440

      _STATISTICS_WRITING_APP: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_APP-eng: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_DATE_UTC: 2017-07-17 02:38:44

      _STATISTICS_WRITING_DATE_UTC-eng: 2017-07-17 02:38:44

      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

    Stream #0:2(eng): Subtitle: subrip

    Metadata:

      BPS             : 55

      BPS-eng         : 55

      DURATION        : 01:01:16.000000000

      DURATION-eng    : 01:01:16.000000000

      NUMBER_OF_FRAMES: 758

      NUMBER_OF_FRAMES-eng: 758

      NUMBER_OF_BYTES : 25468

      NUMBER_OF_BYTES-eng: 25468

      _STATISTICS_WRITING_APP: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_APP-eng: mkvmerge v9.3.1 ('Mask Machine') 64bit

      _STATISTICS_WRITING_DATE_UTC: 2017-07-17 02:38:44

      _STATISTICS_WRITING_DATE_UTC-eng: 2017-07-17 02:38:44

      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mp4: No such file or directory


2017-08-06 15:34:59 - uTorrentPostProcess - ERROR - Error converting file D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT.mkv.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sickbeard MP4 Automator\uTorrentPostProcess.py", line 142, in <module>
    ignore.append(output['output'])
TypeError: 'bool' object has no attribute '__getitem__'
2017-08-06 15:34:59 - uTorrentPostProcess - INFO - Passing D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert directory to Sonarr.
2017-08-06 15:34:59 - autoprocess.sonarr - INFO - Sonarr notifier started.
2017-08-06 15:34:59 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert'.
2017-08-06 15:34:59 - autoprocess.sonarr - INFO - Sonarr response: queued.
```

**Comment by mdhiggins** [comment]
So I misunderstood the 260 character limit and though it was for a folder name not an entire path
The logic I had used previously is flawed in this case and would not have worked

I just pushed a new commit that attempts to bypass this but I didn't have a good windows box to test it
Should only be activated on windows computers with a >260 character path and then it appends \\?\ as a prefix to the path which apparently in windows bypasses the 260 character limit

**Comment by mdhiggins** [comment]
Additionally you can try having your output directory be named something like 'mp4' instead of convert. Guessit seems to think that 'Convert' is the name of the TV show but something like 'mp4' might not confuse it

**Comment by ozdrummerboy** [comment]
I tested the new code you pushed to fix this issue and the issue unfortunately remains. 

It appears the new code you pushed checks the path length for 260 chars rather than the path + filename.

Additionally it should be check for less than 259 as apparently the char limit is 260 including null terminator.
I changed line 166 in uTorrentPostProcess.py to - 

`if len(os.path.join(settings.output_dir, str(sys.argv[5]))) > 259 and os.name == 'nt':`

This works as a test for a single file, but wouldn't work for multiple file processing in your script. 

This makes the FFMpeg conversion work but Sonarr then doesn't handle the \\?\ prefix and returns this error - 

`Folder/File specified for import scan [\\?\D:\Downloads\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]\Game.of.Thrones.S07E01.Dragonstone.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-GoT[rartv]-convert] doesn't exist.`

**Comment by ozdrummerboy** [comment]
Secondly, i have changed the output_directory to 'MP4' and 'Dog' to avoid Sonarr interpreting the directory as something else but both returned the same errors as previously reported - 

`17-8-12 10:26:09.2|Debug|Parser|Unable to parse MP4`

`17-8-12 10:36:05.3|Debug|Parser|Unable to parse Dog`

Both logs attached.
[sonarr.debug(dog).txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1219420/sonarr.debug.dog.txt)
[sonarr.debug(MP4).txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/1219419/sonarr.debug.MP4.txt)

**Comment by amalafrozalam** [comment]
I'm getting a different kind of error from NZBGet. 

INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: KeyError: 'state'
-- | -- | --
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: log.info("%sSonarr response: %s." % (infoprefix, rstate['state']))
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: File "/home/amal/converter/autoprocess/sonarr.py", line 66, in processEpisode
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: Traceback (most recent call last):
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: 2017-09-18 07:07:18 - autoprocess.sonarr - ERROR - [ERROR] Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: 2017-09-18 07:07:18 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/home/amal/nzbget/completed/sonarr/showname'.
INFO | Mon Sep 18 2017 07:07:18 | NZBGetPostProcess: 2017-09-18 07:07:18 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.

I've checked and the Sonarr API key is correct, Sonarr is definitely running, and requests is definitely installed.

**Comment by CarbonNeuron** [comment]
Huh, this is kinda odd.
Radarr and sonarr now act as if the script does not even tell them to scan the new directory. I can post logs if someone would tell me how. I look in the logs on sonarr and it doesn't say anything about a refresh.
