### ISSUE TITLE
Still trying to process mp4

### ISSUE THREAD

**Issue by jroncalli** [mdhiggins/sickbeard_mp4_automator#969]
I would like to use manual.py against a directory and run it nightly to convert any newly added files. I am using sonarr and radarr in openmediavault in docker images and I could not get the automation to work reliably. When I run it against a directory that is full of already converted mp4, even though I have the convert-mp4 set to false, see output below. This is a directory that has already had manual.py ran against it and everything converted.

Audio bitrate was invalid, defaulting to 256 per channel.
Invalid interal subtitle codec srt, defaulting to 'mov_text'.
64bit Python.
Processing file b'Colony\\Season 1\\Colony - S01E01 - Pilot.mp4'
Matched TV episode as b'Colony' (TVDB ID:284210) S01E01
Processing b'Colony' Season 01 Episode 01 - b'Pilot'
Tagging file: Colony\Season 1\Colony - S01E01 - Pilot.mp4.
Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.
2018-12-29 21:22:41 - qtfaststart - ERROR - This file appears to already be setup for streaming!
QT FastStart did not run - perhaps moov atom was at the start already.

I was wondering is there a way to get it to completely ignore anything with an mp4 extension, since I know that those would be files that I already converted.

Thank You

[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/2716955/autoProcess.ini.txt)

**Comment by Azno** [comment]
Probably not exactly what you are looking for but something like this would probably do the trick:
(for windows, I'm sure you can work it out if you require it a different way)

@echo off
setlocal enableDelayedExpansion
Set Location="D:\TV Shows"
Set PatternName=".*\.mp4"
Set Transcoder="C:\Transcoder\"
for /f "delims=" %%F in ('dir %Location% /s /b /a-d ^| findstr /v /i /e /r %PatternName%') do (
    %Transcoder%manual.py -i "%%F" -a
)

the above ignores anything with a .mp4 extension .

if your on linux then it would translate into similar to


Location="/TV Shows/*/*"
Pattern="*.mp4"
Transcode = /Mp4auto/manual.py

for Convert in (find $Location -type f \( -iname "*.*" ! -iname $Pattern \))
do

$Transcode -i $Convert -a 

done

Not a linux guy so the syntax might be off but you get the picture.

Thanks

Azno~

**Comment by jroncalli** [comment]
Wow, thank you, thank you very much!

**Comment by jroncalli** [comment]
Do you know why almost every file I process gives me the error you see above 'Invalid interal subtitle codec srt, ?

**Comment by mdhiggins** [comment]
Because SRT inside a valid internal / embedded subtitle codec and I'm guessing you have embed subs turned on

**Comment by jroncalli** [comment]
So it's a setting in the autoprocess.ini? If I turn it off will I still get an external .set file created with each conversion?

**Comment by mdhiggins** [comment]
Basically yeah. Embedded subs store the subs as a track in the file (not burned in) otherwise it’ll create an external SRT if the source came with subs

**Comment by jroncalli** [comment]
Awesome, thanks for the info and quick responses!

**Comment by jroncalli** [comment]
I had one more question, when I go to pick a subtitle (I'm using plex), my option is mov_text. Is that the .SRT file that your tool downloaded or is that embedded in the mp4?

**Comment by mdhiggins** [comment]
Embedded, though the tool may be downloading it and embedding it based on your current configuration

**Comment by jroncalli** [comment]
So I could delete the .srt files?  It so,  what would I change in my .ini figure so it sounds just embed them but not create the extra .srt file, or do I just have to manually delete them afterwards?

**Comment by jroncalli** [comment]
> Probably not exactly what you are looking for but something like this would probably do the trick:
> (for windows, I'm sure you can work it out if you require it a different way)
> 
> `@echo off`
> `setlocal enableDelayedExpansion`
> `Set Location="D:\TV Shows"`
> `Set PatternName=".*\.mp4"`
> `Set Transcoder="C:\Transcoder\"`
> `for /f "delims=" %%F in ('dir %Location% /s /b /a-d ^| findstr /v /i /e /r %PatternName%') do (`
> ` %Transcoder%manual.py -i "%%F" -a`
> `)`
> 
> the above ignores anything with a .mp4 extension .
> 
> if your on linux then it would translate into similar to
> 
> `Location="/TV Shows/*/*"`
> `Pattern="*.mp4"`
> `Transcode = /Mp4auto/manual.py`
> 
> `for Convert in (find $Location -type f \( -iname "*.*" ! -iname $Pattern \))`
> `do`
> 
> `$Transcode -i $Convert -a `
> 
> `done`
> 
> Not a linux guy so the syntax might be off but you get the picture.
> 
> Thanks
> 
> Azno~
Anzo, 
Thank you for the batch file. I was wondering if you could explain it to me a little though. The switches in the for loop after location /s /b /a-d   are those For switches? Where could I find a little info on them. I am really just asking to learn. For patternname, i was curious how that particular string excludes .mp4. 

Thank you.

**Comment by Azno** [comment]
Hiya,
 Sorry, it was doggy take out day just got back in.

`dir %Location% /s /b /a-d` 
/s = Displays files recursively, traversing any subdirectories.
/b = Uses bare format (no heading information or summary, just the information itself).
/a-d = NOT Folders (Files only)

`findstr /v /i /e /r %PatternName%'`
/v = Print only lines that do NOT contain a match.
/i = Case-insensitive search. (dont really need this)
/e = Match pattern if at the END of a line.
/r = Evaluate as a regular expression.

to make it ignore .srt change this:

`Set PatternName=".*\.mp4"`

to

`Set PatternName=".*\.mp4 .*\.srt"`

to add even more just add a space followed by the next lookup string so for three it would be...

`".*\.mp4 .*\.srt .*\.txt"`

Cheers

Azno~

**Comment by jroncalli** [comment]
@Azno that worked great, thank you again.

**Comment by Azno** [comment]
@jroncalli np I'm glad you've sorted it. :)

**Comment by jroncalli** [comment]
I wanted to share a linux version of the script in case anyone want's to use it. 

This will ignore .mp4 and .srt files. You will of course have to change location to match yours. I named it movieconvert.sh . Make sure you chmod +x on the file to make it executable. I have it running nightly as a cron job in openmediavault. 

#!/bin/bash

Location="/srv/4fb31e81-35c5-42de-acb2-9bb80b7ec9b7/plexmedia/movies"
Pattern="*.mp4"
Pattern1="*.srt"
Transcode="/sharedfolders/data/mp4auto/manual.py"

find "$Location" -type f \( -iname "*.*" ! -iname "$Pattern" ! -iname "$Pattern1" \) -exec "$Transcode" -i {} -a ';'
